%ECHO OFF
%ECHO Starting SMS System
PAUSE
START "FIRE SPRINKLER CONTROLLER CONSOLE" /MIN /NORMAL java SprinklerController %1
START "FIRE ALARM CONTROLLER CONSOLE" /MIN /NORMAL java FireAlarmController %1
START "FIRE SENSOR CONSOLE" /MIN /NORMAL java FireSensorConsole %1

